version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    platform: linux/amd64
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password